

from pydantic import BaseModel
from typing import Optional


class TelemetryData(BaseModel):
    
    timestamp: str
    zone: str
    altitude: float = 50.0       # metres above ground
    drone_status: str = "active"  # active | returning | charging


class FrameEvent(BaseModel):
    
    frame_id: int
    timestamp: str
    zone: str
    raw_caption: str              # raw text output from the VLM — never throw this away
    object_type: str              # 'vehicle' | 'person' | 'unknown'
    color: Optional[str] = None   # only meaningful for vehicles
    vehicle_model: Optional[str] = None  # truck, car, van, motorcycle etc
    action: Optional[str] = None  # entering, exiting, parked, loitering, walking
    person_count: int = 0         # number of people visible in this frame
    suspicious: bool = False      # VLM or LLM flagged something unusual


class Alert(BaseModel):
    """
    Generated by the alert engine when a rule is triggered.
    """
    timestamp: str
    alert_type: str   # 'loitering' | 'repeated_vehicle' | 'unauthorized_access' | 'suspicious_activity'
    severity: str     # 'HIGH' | 'MEDIUM' | 'LOW'
    message: str      # human-readable alert description shown in UI
    frame_id: int     # links back to the event that triggered this
    zone: str